language: python
python:
  - "2.7"

before_install:
     # add for profile
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq


install:
  # add for profile
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - pip install nose-cprof
    - pip install properform

    - pip install . --use-mirrors
script:
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_udiskie_a2b88ef6da_4
  - python -m properform Push 47.88.50.110:15554 asdf_udiskie_a2b88ef6da_4 ./profile_udiskie_a2b88ef6da_4
 #2017-09-18 14:19:58 modified at 0 #2017-09-18 14:20:03 modified at 1 #2017-09-18 14:20:07 modified at 2 #2017-09-18 14:20:12 modified at 3 #2017-09-18 14:20:16 modified at 4