language: python

# Restrict testing to system native python versions.
# This means that binary distributions can be used for the dependencies.
# Travis runs on Ubuntu 12.04 LTS currently. :(
python:
  # - "2.5"
  # - "2.6"
  - "2.7"


# Inherit system site packages for use in virtualenv:
virtualenv:
  system_site_packages: true

# Install dependencies that are hard to install:
# (these can't be built via setuptools)
before_install:
  - sudo apt-get -qy update
  - sudo apt-get -qy install
            python-gobject python3-gobject
            python-dbus python3-dbus

  # Development files for custom builds:
  # (build works for python2.x but fails on python3 since configure scripts
  # can't find python headers in virtualenv)
  # - sudo apt-get -qy install
  #           libdbus-1-dev libdbus-glib-1-dev
  #           gobject-introspection libgirepository1.0-dev
  #           libcairo2-dev python-cairo-dev python3-cairo-dev

  # add for profile
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

  # Manually build dependencies (but don't insist):
  # - PREFIX=$VIRTUAL_ENV ./build_requirements.sh || true

  # For testing:
  - pip install python-dbusmock

  # Install package
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)

# Actual tests:
script:
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_udiskie_1f924863c3_1
  - python -m properform Push 47.88.50.110:15554 asdf_udiskie_1f924863c3_1 ./profile_udiskie_1f924863c3_1
 #2017-09-18 13:51:33 modified at 0 #2017-09-18 13:51:37 modified at 1